### ISSUE TITLE
Unneccessary local download

### ISSUE THREAD

**Issue by plutocrat** [bryankaraffa/vestacp-admin-scripts#1]
Hi,
Just an idea but instead of downloading wordpress locally and uploading it to the server, wouldn't it be easier to just run the commands on the remote server ... eg. 
ssh user@server 'cd /path/to/root ; wget http://wordpress.org/latest.tgz ; gunzip latest.tgz ; rm latest.tgz' 
... etc.

**Comment by bryankaraffa** [comment]
Yes it would.  I am no longer maintaining these scripts so feel free to make a PR with the suggested enhancements
